# Generated by Django 2.2.2 on 2019-06-30 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artigo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='curtidas',
        ),
    ]
