# Generated by Django 2.2.2 on 2019-06-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigo', '0002_auto_20190617_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
