# Generated by Django 2.0.7 on 2019-05-14 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='questionario',
        ),
    ]
