# Generated by Django 2.0.7 on 2019-05-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('dataResposta', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('D', 'Disponível'), ('I', 'Indisponível'), ('R', 'Respondido')], max_length=1)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
