# Generated by Django 2.2 on 2019-06-20 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0002_auto_20190514_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='questionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='questionario.Questionario'),
        ),
    ]
