# Generated by Django 2.2.2 on 2019-06-30 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0004_auto_20190628_1654'),
        ('questionario', '0003_auto_20190619_2151'),
    ]

    operations = [
    ]
