# Generated by Django 2.0.7 on 2019-05-14 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0002_remove_categoria_questionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=15)),
                ('descricao', models.CharField(max_length=30)),
                ('dicas', models.TextField()),
                ('estado', models.CharField(choices=[('DI', 'Disponível'), ('I', 'Indisponível'), ('EE', 'Em Espera'), ('EA', 'Em Andamento'), ('C', 'Concluída'), ('B', 'Bloqueada'), ('DE', 'Desbloqueada')], max_length=2)),
                ('pontos', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.Categoria')),
            ],
        ),
    ]
