# Generated by Django 2.2.2 on 2019-07-02 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='pontos',
        ),
    ]
