# Generated by Django 2.0.7 on 2019-05-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conquista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeConquista', models.CharField(max_length=50)),
                ('disponivel', models.BooleanField(default=False)),
                ('conteudo', models.FileField(upload_to='conquista/')),
            ],
        ),
    ]
