# Generated by Django 2.2.2 on 2019-06-30 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atividade', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conquista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.ManyToManyField(blank=True, to='atividade.Atividade')),
                ('conquista', models.ManyToManyField(blank=True, to='conquista.Conquista')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
