# Generated by Django 2.0.7 on 2019-05-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0001_initial'),
        ('questionario', '0002_auto_20190514_0004'),
        ('artigo', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='artigo',
            field=models.ManyToManyField(to='artigo.Artigo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='atividade',
            field=models.ManyToManyField(to='atividade.Atividade'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='questionario',
            field=models.ManyToManyField(to='questionario.Questionario'),
        ),
    ]
