# Generated by Django 2.0.7 on 2019-05-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conquista', '0001_initial'),
        ('usuario', '0002_auto_20190514_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='conquista',
            field=models.ManyToManyField(to='conquista.Conquista'),
        ),
    ]
