# Generated by Django 2.2.2 on 2019-06-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20190602_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='artigo',
            field=models.ManyToManyField(blank=True, to='artigo.Artigo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='atividade',
            field=models.ManyToManyField(blank=True, to='atividade.Atividade'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='conquista',
            field=models.ManyToManyField(blank=True, to='conquista.Conquista'),
        ),
    ]
