# Generated by Django 2.2 on 2019-06-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0003_auto_20190627_1634'),
        ('usuario', '0005_auto_20190602_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pergunta',
            field=models.ManyToManyField(to='questionario.Pergunta'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='artigo',
            field=models.ManyToManyField(blank=True, to='artigo.Artigo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='atividade',
            field=models.ManyToManyField(blank=True, to='atividade.Atividade'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='conquista',
            field=models.ManyToManyField(blank=True, to='conquista.Conquista'),
        ),
    ]
