# Generated by Django 2.2.2 on 2019-06-30 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_auto_20190628_1654'),
        ('usuario', '0006_auto_20190619_1453'),
    ]

    operations = [
    ]
